### ISSUE TITLE
domain not working on web.roblox.com and only the log in page

### ISSUE THREAD

**Issue by unfloofy** [anthony1x6000/ROBLOX2016stylus#12]
i do not know why this is happening but when i copy-paste the theme into stylus [or use the usertyles.world link]
but when i use it the theme does not show up at all and only works at the log in page

**Comment by anthony1x6000** [comment]
Sorry about that, it should be working now. Just had to change web-prefix to domain on line 9.

**Comment by unfloofy** [comment]
ok thank you
