### ISSUE TITLE
No Robux icon next to Premium subscription Robux buttons on "Buy Robux" page.

### ISSUE THREAD

**Issue by Ten2O** [anthony1x6000/ROBLOX2016stylus#15]
## [Released](https://github.com/anthony1x6000/ROBLOX2016stylus/releases) CSS bug report

Robux icon is missing on the premium subscription buttons to buy Robux on the "Buy Robux" page.

1. Go to the "Buy Robux" page.
2. Notice the odd looking green buttons, text uncentered as if there should be an icon to the left of it.

![ODD™ Looking Green Buttons](https://user-images.githubusercontent.com/63513830/148558012-64da4d85-652a-4ae5-a55e-1fb14ffdea06.png)

It should look like something like this quick mockup I made.

![somethinglikethis](https://user-images.githubusercontent.com/63513830/148559982-0d94cba3-9c53-436a-beae-8f91cdaf1bcc.jpg)

 - OS: Windows 10 21H2
 - Browser: [Ungoogled Chromium](https://github.com/ungoogled-software/ungoogled-chromium-windows), though I can reproduce this exact issue with Firefox as well.
 - Script Version: Release 1.2.0
 - Display resolution: 2560x1440

**Comment by anthony1x6000** [comment]
It should, hopefully, be fixed in the latest [patch](https://github.com/anthony1x6000/ROBLOX2016stylus/releases/tag/1.2.0) :)

**Comment by Ten2O** [comment]
> It should, hopefully, be fixed in the latest [patch](https://github.com/anthony1x6000/ROBLOX2016stylus/releases/tag/1.2.0) :)

It is fixed on the non-premium page now, but if you have roblox premium it is still missing.


![burger](https://user-images.githubusercontent.com/63513830/148584642-315ddc7a-2e76-45f0-8b3b-2895722d00d0.png)


![burger2](https://user-images.githubusercontent.com/63513830/148584648-1dd85c2d-e7be-4825-8bd9-e348793a66c2.png)

**Comment by anthony1x6000** [comment]
Sorry I don't have premium. I tried to get it to show by messing with javascript variables but that didn't do anything. 
If you're using the unreleased style, edit it and comment out line [516](https://github.com/anthony1x6000/ROBLOX2016stylus/blob/32e00bf559ee5532e9ab4ee81a1cd20f1476c241/stylustheme.css#L516)
Should look like
```
.light-theme .icon-default-economy-28x28, .light-theme .icon-robux-28x28, .light-theme .icon-robux-gold-28x28, .light-theme .icon-robux-white {
/*     background-image: url(https://svgur.com/i/GuZ.svg); */
    background-size: 56px;
}
```
after commenting it out.
