### ISSUE TITLE
robux counter and topbar buttons kind of broken

### ISSUE THREAD

**Issue by SquidBoi84** [anthony1x6000/ROBLOX2016stylus#16]
roblox seems to have made a site update that broke the robux counter and the buttons on the top left of the screen. theyre probably not meant to be looking like this

![image](https://user-images.githubusercontent.com/75950063/156898225-12455dc4-0637-455e-ae89-f3c964f8a925.png)
![image](https://user-images.githubusercontent.com/75950063/156898096-fc8dab06-114b-4423-9ee5-2cd1e00802a1.png)

windows
firefox
1.2.1.1
1366x768

**Comment by anthony1x6000** [comment]
It should be fixed now

**Comment by SquidBoi84** [comment]
yeah it works now

**Comment by SquidBoi84** [comment]
although another thing i just noticed was that when you open the menu on the left the three lines button square doesnt go away
![image](https://user-images.githubusercontent.com/75950063/156902412-879570b6-57c0-476d-874e-9c5190f08393.png)
![image](https://user-images.githubusercontent.com/75950063/156902415-4424519c-7470-41c3-97ea-4d6e9ee4c4ee.png)

**Comment by anthony1x6000** [comment]
maybe it's fixed now?

**Comment by SquidBoi84** [comment]
yeah its pretty much fixed now i guess
