### ISSUE TITLE
Groups page displays no text under groups

### ISSUE THREAD

**Issue by retrostalgia** [anthony1x6000/ROBLOX2016stylus#18]
Groups on https://www.roblox.com/search/groups don't show any text.
Although the text is still there, as you can drag over it and copy it, it isn't visible.
![image](https://user-images.githubusercontent.com/111193347/184503588-0afdd050-d6e3-4436-8184-b744c77a5da1.png)

**Comment by anthony1x6000** [comment]
The issue should be fixed \
The group search now looks like [this](https://i.ibb.co/DLQTXzx/image.png)

**Comment by retrostalgia** [comment]
Thanks, it's working. Although, I very recently found 2 other issues.

- Going to any users profile that has premium will not show the premium logo, but will instead show a blank space. (Speaking of which, would it be possible to have the premium logo replaced with the builders club logo?)
![image](https://user-images.githubusercontent.com/111193347/184521156-2cc1e802-e649-4794-b72f-ee283b620c4a.png)

- The sign up page doesn't show any background or anything, just gray.
![image](https://user-images.githubusercontent.com/111193347/184521186-23350cb1-206c-4ce1-a9c5-0c05ced4bf25.png)

**Comment by anthony1x6000** [comment]
Images should be back now same with OBC image replacing the premium icon

**Comment by retrostalgia** [comment]
Thanks
