### ISSUE TITLE
New Roblox logo shows up on sign up page instead of old

### ISSUE THREAD

**Issue by retrostalgia** [anthony1x6000/ROBLOX2016stylus#19]
## [Released](https://github.com/anthony1x6000/ROBLOX2016stylus/releases) CSS bug report
The new Roblox logo shows on the sign up page instead of the old one.

**To Reproduce**
https://www.roblox.com/ (logged out ofc)
1. Click the link
2. It's literally right there

![image](https://user-images.githubusercontent.com/111193347/188260606-e1d824be-c55e-4f60-a932-a29eb9037b1f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Brave
 - Script Version 1.2.2.5
 - 1920 x 1080

*not a issue but i thought i'd but it here*
would it be possible to add the OBC theme (maybe as another download that downloads as the OBC version), like the one seen here? 
![image](https://user-images.githubusercontent.com/111193347/188260676-0acdb540-25a3-4397-8512-d0503e11d21a.png)

**Comment by anthony1x6000** [comment]
Should [look closer to 2016 now](https://files.catbox.moe/p6tpnj.jpg) in the new release. \
I'll work on making an OBC theme. It seems cool.

**Comment by retrostalgia** [comment]
Thanks a ton! Also good to know that's being worked on
