### ISSUE TITLE
"Hello, User!" userscript shows a content deleted icon. / Messages page is broken (2 issues)

### ISSUE THREAD

**Issue by retrostalgia** [anthony1x6000/ROBLOX2016stylus#21]
## [Released](https://github.com/anthony1x6000/ROBLOX2016stylus/releases) CSS bug report
The "Hello, User!" userscript doesn't show an avatar but just shows the content deleted icon

**To Reproduce**
https://www.roblox.com/home
1. Install the userscript
2. Go to the Roblox home page

![image](https://user-images.githubusercontent.com/111193347/188283770-e53ac97b-a9f6-40c2-9596-49381a52492f.png)

**To Reproduce**
https://www.roblox.com/my/messages/#!/inbox
1. Go to the page
2. Open eyes

What it looks like now:
![image](https://user-images.githubusercontent.com/111193347/188284108-205bbe5e-6566-4eb0-8fe5-9811f9e43d99.png)
What it should look like (if possible, if not just make it not duplicated):
![image](https://user-images.githubusercontent.com/111193347/188284123-2d8100c6-356f-40a4-9d7c-27288aad2238.png)

 - OS: Windows
 - Browser: Brave
 - Script Version 1.2.3 (although it doesn't affect anything, it does the same thing whether or not you have the 2016 script)
 - Display resolution: 1928 x 1080

**Comment by retrostalgia** [comment]
I've noticed that sometimes it will show the avatar, but it's not consistent.

**Comment by anthony1x6000** [comment]
The problem with the userscript is kind of a problem with how I wrote the code and tampermonkey. Clicking off the page seems to break the page load function to redefine the profile avatar variable image thingy. Should be fixed now though. 

I'll work on getting the message page to look better.

**Comment by retrostalgia** [comment]
Thanks, I also made a suggestion relating to the login page in the discussion, if you wanna check that out

**Comment by anthony1x6000** [comment]
The roblox logo should be back now for messages. I'll check out the discussion

**Comment by retrostalgia** [comment]
Alright, thanks!
