### ISSUE TITLE
Robux icon next to "Was XXX" on limiteds is broken / BC icon is premium UGC items is glitched

### ISSUE THREAD

**Issue by retrostalgia** [anthony1x6000/ROBLOX2016stylus#22]
## [Released](https://github.com/anthony1x6000/ROBLOX2016stylus/releases) CSS bug report
The Robux icon that shows right next to the "Was (original price here)" on limiteds is broken,

**To Reproduce**
1. Go to https://www.roblox.com/catalog
2. Find a limited
3. See error

![image](https://user-images.githubusercontent.com/111193347/188285839-ad008046-2a9a-4fee-9a45-442330a2d50c.png)

**To Reproduce** (2)
1. Go to https://www.roblox.com/catalog
2. Click on premium and select anything (or just find a premium item)
![image](https://user-images.githubusercontent.com/111193347/188285857-fd3a9fc1-0472-40ac-a506-72dfccae8502.png)

![image](https://user-images.githubusercontent.com/111193347/188285863-6f23e25e-ab35-4eff-a4ca-7e5d0cbfc133.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Script Version: 1.2.3
 - 1920 x 1080

**Comment by anthony1x6000** [comment]
Should be [fixed ](https://files.catbox.moe/2f8xlz.png) now.

**Comment by retrostalgia** [comment]
Thanks for the fix. Although, the problem with the "Was (og limited price)" still happens. And also, I kinda feel like I have to ask, could the premium icon in the catalog be changed the the OBC icon like the icon on profiles?

**Comment by anthony1x6000** [comment]
haha sorry I just instinctively scrolled to the bottom of the page. Ill fix the limited prices stuff

**Comment by retrostalgia** [comment]
Alr thanks lol, thanks for doing all the fixes and stuff I've been suggesting, fun to watch this theme slowly get better and better
