### ISSUE TITLE
Stylish turns off when i refresh page

### ISSUE THREAD

**Issue by himeunderwater** [anthony1x6000/ROBLOX2016stylus#23]
When i try using it and i go to a different page it gets rid of the 2016 thing and makes it the current one and doesnt switch back unlees i enable it on the extension

**Comment by retrostalgia** [comment]
use stylus, stylish is mid.

**Comment by anthony1x6000** [comment]
Like [retrostalgia](https://github.com/retrostalgia) said, it might be a problem with the extention you're using and maybe your browser. 
I use [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) and a Chromium based browser.
