### ISSUE TITLE
Robux icon for private servers on the "Configure Place" page is broken

### ISSUE THREAD

**Issue by retrostalgia** [anthony1x6000/ROBLOX2016stylus#24]
## [Unreleased/Beta](https://github.com/anthony1x6000/ROBLOX2016stylus/blob/main/unreleasedChanges.md) CSS Bug report
The Robux icon on the configure place page for private servers is broken.

**To Reproduce**
1. Go to https://roblox.com/develop
2. Go to any game, click the settings icon, and click "configure start place".
![image](https://user-images.githubusercontent.com/111193347/189783942-89c9adc5-6665-4cd7-a9be-aaa9f311e4c4.png)
3. Go to the "access" tab and make sure private servers are enabled
![image](https://user-images.githubusercontent.com/111193347/189784041-6256e8a1-dc15-4f6b-ae13-9cf183bac1f0.png)
4. See issue
![image](https://user-images.githubusercontent.com/111193347/189784097-e1eadf5c-fb1f-4173-9e5f-a0a83cc46c9d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Script Version: 1.2.3.1
 - Display resolution: 1920 x 1080

**Comment by retrostalgia** [comment]
That release'll come soon, I have a lot of issues to report lol

**Comment by anthony1x6000** [comment]
<img src="https://c.tenor.com/zSqo3w4cnZkAAAAi/emoji-grief.gif" />

**Comment by retrostalgia** [comment]
Oh also, didn't see it when making this but it's also broken on the thumbnail page
![image](https://user-images.githubusercontent.com/111193347/189787264-153ae84f-f56b-4695-a607-a5bad3a4e4f4.png)

**Comment by anthony1x6000** [comment]
That should be fixed with the thing i pushed to the unreleased style

**Comment by anthony1x6000** [comment]
> Oh also, didn't see it when making this but it's also broken on the thumbnail page ![image](https://user-images.githubusercontent.com/111193347/189787264-153ae84f-f56b-4695-a607-a5bad3a4e4f4.png)

That should be fixed with the thing i pushed to the unreleased style
