### ISSUE TITLE
Text displaying group member count is broken when viewing groups on someones profile

### ISSUE THREAD

**Issue by retrostalgia** [anthony1x6000/ROBLOX2016stylus#25]
## [Unreleased/Beta](https://github.com/anthony1x6000/ROBLOX2016stylus/blob/main/unreleasedChanges.md) CSS Bug report
Text displaying group member count is broken when viewing groups on someones profile

**To Reproduce**
1. Go to a profile of someone who is in any group
2. Scroll down and find the groups
![image](https://user-images.githubusercontent.com/111193347/189784951-7f561ba4-5fad-4f12-948e-3fa37cf97984.png)
3. Click the button with 6 small squares 
![image](https://user-images.githubusercontent.com/111193347/189784991-a778c52b-4131-4996-ad2d-997e4f6703cf.png)
4. See issue

![image](https://user-images.githubusercontent.com/111193347/189785026-d0251871-578c-4128-962e-44186926a98d.png)

 - OS: Windows
 - Browser: Firefox
 - Script Version: 1.2.3.1
 - Display resolution: 1920 x 1080

**Comment by anthony1x6000** [comment]
Probably fixed now
![image](https://user-images.githubusercontent.com/33004321/189787967-19c3da66-4b11-45e1-afeb-f4aadf58da55.png)

**Comment by retrostalgia** [comment]
Good to know, also, would it be possible to use the theme to change Roblox's header or whatever its called (so it says "ROBLOX", instead of "Roblox") and to change the favicon so it's the old one?

**Comment by anthony1x6000** [comment]
I'd need to make a userscript for that. Ive been meaning to do that but never got around to it. Probably wont take too long

**Comment by retrostalgia** [comment]
Good to know, I hacked together my own extension that replaces the favicon by taking one that replaces the google favicon, and changed the url it changes and the favicon, but I'm sure it could be better, and I'm also not sure how to change "Roblox", to "ROBLOX"

**Comment by anthony1x6000** [comment]
I made something that changes the title along with the favicon. \
https://github.com/anthony1x6000/ROBLOX2016stylus/blob/main/favicon.user.js \
Should work fine

**Comment by retrostalgia** [comment]
Weird, the icon works fine on the home page but it doesn't work anywhere else on the site, and the "ROBLOX" change barely ever works, and usually instantly reverts back to "Roblox" after a page is loaded

**Comment by anthony1x6000** [comment]
Script now runs after the page is loaded. Should be fixed. There will be a small delay before the script is executed while tampermonkey waits for the page to load.

**Comment by retrostalgia** [comment]
Works fine now, thanks
