### ISSUE TITLE
Item names in the catalog don't go to a new line and instead display "..."

### ISSUE THREAD

**Issue by retrostalgia** [anthony1x6000/ROBLOX2016stylus#26]
## [Unreleased/Beta](https://github.com/anthony1x6000/ROBLOX2016stylus/blob/main/unreleasedChanges.md) CSS Bug report
This definitely isn't a major issue or anything but I thought I'd point it out since it breaks a 2016 catalog theme I use.
Item names in the catalog don't go to a new line and instead display "..."

1. Go to https://www.roblox.com/catalog
2. See issue

![image](https://user-images.githubusercontent.com/111193347/189785795-981d0d90-4b5c-4055-acba-5b50993f71a0.png)

 - OS: Windows
 - Browser: Firefox
 - Script Version: 1.2.3.1
 - Display resolution: 1920 x 1080

**Comment by anthony1x6000** [comment]
Sorry I dont see the issue. Can you explain it further?

**Comment by retrostalgia** [comment]
Honestly thinking back I'm not sure why I didn't put this in discussions but I mentioned this since I use a theme that brings back the old catalog, and because this theme makes names for games/catalog items only go on 1 line, and then cut off. It's also inaccurate to 2016 I guess but that's a big stretch
