### ISSUE TITLE
"Buy Robux" page is inconsistant between accounts

### ISSUE THREAD

**Issue by retrostalgia** [anthony1x6000/ROBLOX2016stylus#27]
## [Unreleased/Beta](https://github.com/anthony1x6000/ROBLOX2016stylus/blob/main/unreleasedChanges.md) CSS Bug report
The "Buy Robux" page is inconsistent between accounts

**To Reproduce**
1. Go to https://www.roblox.com/upgrades/robux
2. See issue

Main account: 
![image](https://user-images.githubusercontent.com/111193347/189786733-c2eccdab-9d9b-4b48-a322-b90cc9aa61d4.png)

Any account besides my main: 
![image](https://user-images.githubusercontent.com/111193347/189786599-c32b0936-9411-4ab1-9dc6-bfa32623487d.png)

 - OS: Windows
 - Browser: Firefox
 - Script Version: 1.2.3.1
 - Display resolution: 1920 x 1080

Also, the "Want more Robux?" button is gone if I'm not on my main.
No clue what causes this, if there's something you want me to test lmk

**Comment by anthony1x6000** [comment]
<img src="https://litter.catbox.moe/r55tvn.png" /> The buy robux screen looks like your alternate. Do you have premium on your main?

**Comment by anthony1x6000** [comment]
Or is ur main on web.roblox.com as the root domain?

**Comment by retrostalgia** [comment]
I don't have premium currently (used to), and the domain isn't web. on either of the accounts tested.

**Comment by retrostalgia** [comment]
I'm going to guess Roblox itself is at fault for this and not the theme
