### ISSUE TITLE
Roblox Download page has the new logo and is inaccurate

### ISSUE THREAD

**Issue by retrostalgia** [anthony1x6000/ROBLOX2016stylus#28]
## [Unreleased/Beta](https://github.com/anthony1x6000/ROBLOX2016stylus/blob/main/unreleasedChanges.md) CSS Bug report
The Roblox Download page (which I didn't even know existed but I'm still mentioning it) still has the new logo, and is slightly inaccurate.

1. Go to https://www.roblox.com/download
2. See issue

Current: 
![image](https://user-images.githubusercontent.com/111193347/189788353-3cbf5a30-173b-4552-af04-6d097e022dc7.png)

Old (archive.org): 
![image](https://user-images.githubusercontent.com/111193347/189788437-d8f6f6f4-aef2-410d-a2d6-5f23322ad74d.png)

 - OS: Windows 10
 - Browser: Firefox
 - Script Version: 1.2.3.1
 - Display resolution: 1920 x 1080

This is like the least visited page in Roblox history but I wanna report it anyway cuz funni

**Comment by anthony1x6000** [comment]
ya i dont think ive ever seen that page. I'll fix the logo but adding more code to fix the button just adds to the size of the file. The style is probably going to approach the 100kb compressed limit in userstyles soon.

**Comment by retrostalgia** [comment]
What'll you do when that happens? Is it possible to split this theme into 2 separate files or something like that?

**Comment by anthony1x6000** [comment]
Ill figure that out when the time comes. Theres a lot of unnecassary code in there that can be removed so ill start with that.
