### ISSUE TITLE
robux appearing twice at the top

### ISSUE THREAD

**Issue by david12084** [anthony1x6000/ROBLOX2016stylus#30]
Hi, I'm sorry if my English is not correct, I'm using a translator.

As you can see in the image above, "robux" appears twice instead of just once.
![imagen_2022-11-08_192709831](https://user-images.githubusercontent.com/117780951/200689581-161a8558-a1ca-45b3-98ea-12706f63a343.png)

attached files

**Comment by anthony1x6000** [comment]
is your website domain web.roblox.com?
