### ISSUE TITLE
web.roblox.com (under 13) doesnt work, only roblox.com

### ISSUE THREAD

**Issue by cutekasumi** [anthony1x6000/ROBLOX2016stylus#31]
i made my account birth year 2015 by accident and the under 13 website is web.roblox.com
![Home - Roblox - Google Chrome 11_28_2022 12_10_22 AM](https://user-images.githubusercontent.com/100105791/204216021-82cbd2b9-04d4-4231-8128-4582dc52a636.png)
^ alt account i never use
![Home - Roblox - Google Chrome 11_28_2022 12_11_07 AM](https://user-images.githubusercontent.com/100105791/204216077-070fb2cf-ac67-4e5a-a775-bedcb4227ca8.png)
^ main

**Comment by anthony1x6000** [comment]
Turn off dark mode on your main - that should fix it. I'll try to figure out the web.roblox.com thing later.

**Comment by anthony1x6000** [comment]
The style should be fine on web.roblox.com. I think it's dark mode in your settings that's messing everything up. 
![image](https://user-images.githubusercontent.com/33004321/204692682-9a11bdb4-2848-4917-8ce3-0e84d29c24b2.png)
