### ISSUE TITLE
Five bugs i found.

### ISSUE THREAD

**Issue by lmao26354** [anthony1x6000/ROBLOX2016stylus#38]
## [Released](https://github.com/anthony1x6000/ROBLOX2016stylus/releases) CSS bug report
**The Bugs**
First bug: The ROBUX text when buying a private server isn't green but black.
Second bug: Catalog offers under limited items have the new ROBUX logo and black text.
Third bug: The average price on the price chart doesn't have the green ROBUX logo and green text.
Fourth bug: a miniature Premium logo on catalog items is not replaced with the OBC logo.
Fifth bug: On the Buy ROBUX page, the premium logo is not replaced with the OBC logo.

[Link to the first bug. ](https://www.roblox.com/games/264431831/Speed-Run-4-Classic#!/game-instances)
The error is located under the Private Servers section.

[Link to the second and third bug. ](https://www.roblox.com/catalog/13032232281/Banana-Coin)
Second bug: Scroll down to the Resellers tab.
Third bug: Scroll down to the Price Chart and look at the Average Price.

[Link to the fourth bug. ](https://www.roblox.com/catalog?Category=1&salesTypeFilter=3)
Wrong icon next to the item names.

[Link to the fifth bug. ](https://www.roblox.com/upgrades/robux)
Wrong icon next to the "Subscribe and Get More" title.

**What it should look like**
[What the first bug should look like. ](https://i.imgur.com/nhX6Y3V.png)

[What the second and third bug should look like. ](https://web.archive.org/web/20160910153332/https://www.roblox.com/catalog/20573078/Shaggy)

[What the fourth bug should look like. ](https://i.imgur.com/RftRIuI.png)

[What the fifth bug should look like. ](https://i.imgur.com/FGtMgHs.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Script Version [1.2.6]
 - Display resolution [2560 x 1440]

**Comment by anthony1x6000** [comment]
I sent a commit to [stylustheme.css](https://github.com/anthony1x6000/ROBLOX2016stylus/blob/main/stylustheme.css) that should fix everything reported. I'll send a release later today or tmrw when everything has been tested.

**Comment by lmao26354** [comment]
Just found another bug.
[Link to the bug.](https://www.roblox.com/catalog/13280164224/Gold-Dollar-Glasses-PLS-DONATE)
Under the ROBUX Price, It says "Get Premium and buy for 74" However the 74 price is black instead of green."

**Comment by lmao26354** [comment]
Literally just found a second bug.
[Link to the second bug.](https://www.roblox.com/upgrades/robux?ctx=navpopover)
The ROBUX price is black instead of green.
[What the second bug should look like.](https://web.archive.org/web/20180704000322/https://www.roblox.com/upgrades/robux?ctx=navpopover)

**Comment by lmao26354** [comment]
I just found a third bug lol.
[Link to the third bug.](https://www.roblox.com/transactions)
Just click through all the subsections, A TON of ROBUX price text is black instead of green.

**Comment by anthony1x6000** [comment]
kk should be fixed now in [stylustheme.css](https://github.com/anthony1x6000/ROBLOX2016stylus/blob/main/stylustheme.css)

I'll make a release tmrw maybe
