### ISSUE TITLE
Broken icon

### ISSUE THREAD

**Issue by g3n3r1c-u53rn4m3** [anthony1x6000/ROBLOX2016stylus#43]
The icon in question is the Roblox Credit icon that is now added. Next to the Robux icon, it appears not white, but black.

A link to the page where the bug is located is preferred. 
1. Go to 'roblox.com/home'
2. Use gift card to get Roblox Credit
3. See error
Please include an image with the bug report. 

<img width="197" alt="Screenshot 2023-12-26 124740" src="https://github.com/anthony1x6000/ROBLOX2016stylus/assets/112830178/34af643b-caff-4751-bfdf-1d55944a24d5">

OS: Windows
Browser Firefox
Script Version 1.2.7
Display resolution 1920 x 1080

**Comment by anthony1x6000** [comment]
I don't have access to the element for the wallet icon. Could you send the class, or better, the entire header element the wallet icon is under? 
Open up inspect element with F12 and then select an element, on Brave (probably Chrome too) it's Ctrl + Shift + C.
![image](https://github.com/anthony1x6000/ROBLOX2016stylus/assets/33004321/736eb98a-d7ec-44e2-9c83-30589974d539)
Then select the wallet icon and send the class it's in. From there I can just invert the icon. 
For example, the robux icon:
![image](https://github.com/anthony1x6000/ROBLOX2016stylus/assets/33004321/2304154d-cf7c-4191-becc-798f2e517fd8)

**Comment by g3n3r1c-u53rn4m3** [comment]
I was able to find the class of the wallet icon.
<img width="334" alt="Screenshot 2023-12-30 111820" src="https://github.com/anthony1x6000/ROBLOX2016stylus/assets/112830178/5215a17f-21e0-418b-ac13-727c352355e5">

**Comment by anthony1x6000** [comment]
Made a commit d8fb5800eee49e40e11e2400eb5b57f37fb7e357. 
Hopefully doing this works
