### ISSUE TITLE
Roblox updates have broken parts of the script

### ISSUE THREAD

**Issue by AttakDoge** [anthony1x6000/ROBLOX2016stylus#46]
## [Released](https://github.com/anthony1x6000/ROBLOX2016stylus/releases) CSS bug report
**Describe the bug**
Description of what the bug is.

**To Reproduce**

Game page showcased in the screenshots below: [Phantom Forces](https://www.roblox.com/games/292439477/Phantom-Forces-PC)

**Screenshots**
![image](https://github.com/anthony1x6000/ROBLOX2016stylus/assets/63970527/c0240c42-22df-4e39-ae29-fb7a79130090)
![image](https://github.com/anthony1x6000/ROBLOX2016stylus/assets/63970527/13576b76-3f6e-431b-905b-0595c583902b)
These images was screenshot today, 4/22, but the website was loaded yesterday.

![image](https://github.com/anthony1x6000/ROBLOX2016stylus/assets/63970527/6da4ed7e-4071-45df-ae56-c8c2b52caf8a)
![image](https://github.com/anthony1x6000/ROBLOX2016stylus/assets/63970527/916fdf63-3a1a-403b-92f2-925f3797bc49)
Screenshot and loaded today, the description and social links have changed, and the script no longer detects them.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, macOS]
 - Browser [e.g. Brave, Firefox]
 - Script Version [e.g. 1.1.2]
 - Display resolution [e.g. 1920 x 1080]

Using Windows 11, Firefox, script version 1.2.8, display res 1920x1080

**Additional context**

I have made a messy and incomplete fix using [a font fix created by cocothemii](https://userstyles.world/style/15885/revert-2024-roblox-font) as a base. See the below text file:
[script.txt](https://github.com/anthony1x6000/ROBLOX2016stylus/files/15070049/script.txt)

Feel free to take anything from the file, it doesn't matter to me if I get credited for anything :)

The screenshots do not have my incomplete fix active.

Overall you have a great script! I've loved it for about a year and a half now!

edit: made some minor changes to the screenshot section

**Comment by anthony1x6000** [comment]
should hopefully be fixed in https://github.com/anthony1x6000/ROBLOX2016stylus/commit/9a0b81630e7f5491732d9bca0884fd5b18e98f7f and https://github.com/anthony1x6000/ROBLOX2016stylus/commit/9dbce0f6a15cc4fd4e61ac2cdc09257198bf7f9b

Just had to replace all gotham font mentions. 

Thanks for the fix script, helped me figure out the issue quicker. 

I'll create a new release soon once I quickly fix the new game cards. Hopefully later tonight.
