### ISSUE TITLE
Theme not compatible with new "recommended" and "top picks" sections

### ISSUE THREAD

**Issue by GoofyGuyWhoCantAnimate** [anthony1x6000/ROBLOX2016stylus#47]
Theme not compatible with new "recommended" and "top picks" sections

How the layout should be:
![image](https://github.com/anthony1x6000/ROBLOX2016stylus/assets/91696629/ed8c920c-cd60-4ff1-a1b6-6dfbebf54100)

How it is:
![image](https://github.com/anthony1x6000/ROBLOX2016stylus/assets/91696629/12a073bf-3f93-408c-a81e-3e6f1d3efd86)

Hopefully this can be resolvedsoon, thanks.

**Comment by anthony1x6000** [comment]
Thanks for opening this issue. This issue should be fixed in the most recent version. What issue would you be using?

**Comment by GoofyGuyWhoCantAnimate** [comment]
Sorry yes I haven't updated in a bit, although it said something about auto-checking. I'll do that now, thank you!
