### ISSUE TITLE
Spritesheet glitchy in messages tab

### ISSUE THREAD

**Issue by GoofyGuyWhoCantAnimate** [anthony1x6000/ROBLOX2016stylus#49]
Hi.. me again....

Ive noticed that when sending a message, instead of the usual send icon, this thing turns up
![image](https://github.com/anthony1x6000/ROBLOX2016stylus/assets/91696629/75c1d1f7-339e-4ff4-aec2-d0c0f1847029)
It has been like this since I first installed the theme

**Comment by anthony1x6000** [comment]
Should be fixed in d3ff523 thanks to @randomguyingithub.
