### ISSUE TITLE
Roblox homepage redesign has messed up parts of the UI

### ISSUE THREAD

**Issue by Setup2134** [anthony1x6000/ROBLOX2016stylus#53]
## [Released](https://github.com/anthony1x6000/ROBLOX2016stylus/releases) CSS bug report
**Describe the bug**
Roblox homepage redesign has messed up parts of the UI.

**To Reproduce**
A link to the page where the bug is located is preferred. 
1. Go to 'https://www.roblox.com/home'
![image](https://github.com/anthony1x6000/ROBLOX2016stylus/assets/138363522/387eb347-36a2-4318-a493-5f3c159d6258)
![image](https://github.com/anthony1x6000/ROBLOX2016stylus/assets/138363522/8b363363-9dbb-43e2-853e-8261ceff88c7)

**What it should look like**
Refer to basically any current image of the homepage on google.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Script Version 1.3.0
 - Display resolution 1600 x 900
**Additional context**
None

**Comment by anthony1x6000** [comment]
Should be fixed now in [latest prerelease](https://github.com/anthony1x6000/ROBLOX2016stylus/raw/main/devDownloads/roblox2016-preLatest.user.css).
