### ISSUE TITLE
Using the proper version of Source Sans Pro

### ISSUE THREAD

**Issue by Diyamund** [anthony1x6000/ROBLOX2016stylus#8]
**Is your feature request related to a problem? Please describe.**
Now, it might sound crazy, but the version of the Source Sans Pro font used by the theme is not the one used in 2016. It smooths differently.

**Describe the feature you'd like**
Remove the current font imports, and add this line at the beginning.
```css
@import url(//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,500,600,700);
```
**Additional context**
**Before:**
![image](https://user-images.githubusercontent.com/44238627/137412034-8657e5d3-a273-407d-b6f1-f9db1578bee1.png)
**After:**
![image](https://user-images.githubusercontent.com/44238627/137412048-8d7ad183-d2a4-4c10-bed7-d72f2a35e734.png)

**Comment by anthony1x6000** [comment]
**Thanks! The font always looked funny; I never knew how to fix it tho.** 

I would try to put you on the [contributor list](https://i.ibb.co/FHKSGZB/image.png) on the side of the repository, but I don't know how to.
